Repository simranquirky/Frontend_templates, pull requests merged in 2021-10, with the labels that each got.

#9 Code Enhancement
  Login_pages/Login_page_1.html
  Login_pages/Login_page_2.html
Labels: enhancement, good first issue, Hactoberfest21, hactoberfest-accepted

#11 Registration form with validation
  Registration form/index.html
  Registration form/script.js
  Registration form/style.css
Labels: enhancement, good first issue, Hactoberfest21, hactoberfest-accepted

#12 Login UI (neumorphism)
  Login_pages/login-page/index.html
  Login_pages/login-page/style.css
Labels: enhancement, good first issue, Hactoberfest21, hactoberfest-accepted

#14 I have completed shopping site
  create a shopping/css/about.css
  create a shopping/css/contact.css
  create a shopping/css/home.css
  create a shopping/css/product.css
  create a shopping/css/purchase.css
  create a shopping/web/about.html
  create a shopping/web/contact.html
  create a shopping/web/home.html
  create a shopping/web/products.html
  create a shopping/web/purchase.html
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#19 I have created a Registration form
  Registration-form-validation/form.css
  Registration-form-validation/index.html
  Registration-form-validation/main.js
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#22 added a restaurant website to this repo
  Restaurant webpage/.DS_Store
  Restaurant webpage/combo.html
  Restaurant webpage/combo_1.html
  Restaurant webpage/combo_2.html
  Restaurant webpage/contact.html
  Restaurant webpage/css/style.css
  Restaurant webpage/dishes.html
  Restaurant webpage/images/.DS_Store
  Restaurant webpage/images/Dosa.jpeg
  Restaurant webpage/images/Idli-Recipe.jpg
  Restaurant webpage/images/InShot_20210327_035901232.jpg
  Restaurant webpage/images/InShot_20210327_040052670.jpg
  Restaurant webpage/images/Noodles.jpg
  Restaurant webpage/images/address.png
  Restaurant webpage/images/cake.jpeg
  Restaurant webpage/images/call.png
  Restaurant webpage/images/close.png
  Restaurant webpage/images/email.png
  Restaurant webpage/images/email2.png
  Restaurant webpage/images/facebook.png
  Restaurant webpage/images/food.jpeg
  Restaurant webpage/images/home-img.jpg
  Restaurant webpage/images/icecream.jpg.crdownload
  Restaurant webpage/images/img1.jpg
  Restaurant webpage/images/instagram.png
  Restaurant webpage/images/menu.png
  Restaurant webpage/images/p1.jfif
  Restaurant webpage/images/p2.jfif
  Restaurant webpage/images/p3.jfif
  Restaurant webpage/images/p4.jfif
  Restaurant webpage/images/pasta.jpg
  Restaurant webpage/images/pic1.png
  Restaurant webpage/images/pic2.png
  Restaurant webpage/images/pizza.jpeg
  Restaurant webpage/images/twitter.png
  Restaurant webpage/index.html
  Restaurant webpage/js/script.js
  Restaurant webpage/review.html
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#23 Added Dashboard
  admin_dashboard_page/dashboard.css
  admin_dashboard_page/dashboard.html
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#21 I have created travel blog site
  travel blog site/index.html
  travel blog site/style.css
  weather/index.html
  weather/style.css
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#27 Adding code
  Registration form/reg/Registration page.html
Labels: good first issue, Hactoberfest21, hactoberfest-accepted

#29 Added Social media dashboard
  Social Media Dashboard/assets/down_icon.png
  Social Media Dashboard/assets/fb_icon.png
  Social Media Dashboard/assets/ig_icon.png
  Social Media Dashboard/assets/profile-image.jpg
  Social Media Dashboard/assets/toggle-off.svg
  Social Media Dashboard/assets/toggle-on.svg
  Social Media Dashboard/assets/twt_icon.png
  Social Media Dashboard/assets/up_icon.png
  Social Media Dashboard/assets/yt_icon.png
  Social Media Dashboard/css/style.css
  Social Media Dashboard/index.html
  Social Media Dashboard/js/script.js
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#32 weather_webpage
  weather_webpage/assets/maud-lapraye-3WZ8UhlpC3c-unsplash.jpg
  weather_webpage/assets/oxa-roxa-tOqoBPr12C8-unsplash.jpg
  weather_webpage/assets/tom-barrett-hgGplX3PFBg-unsplash.png
  weather_webpage/main.html
  weather_webpage/script.js
  weather_webpage/style.css
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#34 Added Footer & Code Rebase
  Portfolio/pritambera2000/CSS/style.css
  Portfolio/pritambera2000/CSS/style.css.map
  Portfolio/pritambera2000/CSS/style.scss
  Portfolio/pritambera2000/index.html
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#36 About page
  About page/about.html
Labels: enhancement, Hactoberfest21, hactoberfest-accepted

#38 sign in page
  Login-pg/login.css
  Login-pg/login.html
  Login-pg/readme.md
  login.css
  login.html
Labels: Hactoberfest21, hactoberfest-accepted

#72 Guess the Number
  Online Game/Guess the Number/index.html
  Online Game/Guess the Number/script.js
  Online Game/Guess the Number/style.css
Labels: Hactoberfest21, hactoberfest-accepted
